global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'banking-app-dev'
    replica: 'primary'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'localhost:9093'

rule_files:
  - 'prometheus-alerts.yml'

scrape_configs:
  - job_name: 'spring-boot-banking-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:8085']
        labels:
          application: 'cbsa-migration'
          environment: 'development'
